project:
  type: website
  preview:
    port: 1111

draft: true

website:
  repo-url: https://github.com/materov/Parametrization-example-ITMO/
  repo-actions: [source]
  # https://quarto.org/docs/websites/website-drafts.html
  draft-mode: visible
  announcement: 
    content: "**Новый сайт** - это анонс!" 
    position: below-navbar 